### ISSUE TITLE
Регистрация пользователей

### ISSUE THREAD

**Issue by atatarov** [omarcompany/rheda-server#23]
Я как незарегистрированный пользователь, хочу зарегистрироваться в системе, что даст мне возможность использовать приложение.

##### Acceptance criteria
На странице регистрации ввожу имя ~логин~ и если логин не занят, то попадаю на главный экран приложения. ~При вводе уже занятого логина выдается ошибка и есть возможность попытаться зарегистрироваться снова~. При закрытии приложения и открытии, должно запомнить что я зарегистрирован и больше не выдавать регистрационную форму (все нужные для дальнейшего использования идентификаторы сохраняются в память). 

Примечание: восстановление пароля, выход из аккаунта, регистрация нового делать сейчас не надо

**Comment by adzeitor** [comment]
Формат для user story можно выбрать такой: https://dev.to/svikashk/writing-user-stories-that-everyone-can-understand-and-helpful-3e6n

Шаблон:
>    As a [role] I can [capability], so that [receive benefit]

Я как пользователь, хочу зарегистрироваться в системе, что даст мне возможность обмениваться с другими пользователями сообщениями.

Далее идут критерии приемки (acceptance criteria):

Шаблон:
> Given [context] when [a specific action is performed] then [a set of consequences should occur]

На странице регистрации ввожу логин и если имя не занято попадаю на главный экран приложения. При вводе уже занятого логина выдается ошибка и есть возможность заново зарегистрироваться.

**Comment by adzeitor** [comment]
В техническом плане сейчас можно просто выдывать UUID при регистрации с любым логином, можно вообще логины не использовать -- пускать всех. Мы же только начинаем ;)
